# Database Configuration (Data Source)
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/NewsLogicServer
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin