spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/NewsLogicServer
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    show-sql: true