spring:

  # Import configuration with secrets and settings
  profiles:
    active: dev

  # Hibernate Settings
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  #liquibase
  liquibase:
    changelog: db/changelog/V1__Default_Models.sql

  logging:
    level:
      org.springframework.beans.factory: DEBUG
      org.springframework.context.annotation: DEBUG