spring:

  # Import configuration with secrets and settings
  profiles:
    active: dev

  # Hibernate Settings
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

      search:
        backend:
          type: lucene
          directory:
            root: ./indexes

  #liquibase
  liquibase:
    changelog: db/changelog/changelog.xml

  logging:
    level:
      org.springframework.beans.factory: DEBUG
      org.springframework.context.annotation: DEBUG

#Cache configuration
cache:
  default:
    type: lfu #or lru
    capacity: 200

#starter-log
  performance:
    monitor:
      enabled: true
      minExecutionTime: 0 #time of method