spring:

  # Import configuration with secrets and settings
  profiles:
    active: dev

  # Hibernate Settings
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true

  #liquibase
  liquibase:
    changelog: db/changelog/V1__Default_Models.sql